# Generated by Django 6.1.1 on 2026-09-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la mascota', max_length=100)),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('conejo', 'Conejo'), ('loro', 'Loro'), ('hamster', 'Hámster'), ('pez', 'Pez'), ('otro', 'Otro')], default='perro', max_length=20)),
                ('edad', models.PositiveIntegerField(help_text='Edad en años')),
                ('estado_vacunacion', models.CharField(choices=[('al_dia', '✅ Al día con vacunas'), ('pendiente', '⚠️ Pendiente de vacunas'), ('alergia', '🔶 Alergia a vacunas')], default='pendiente', max_length=20)),
                ('fecha_ultima_vacuna', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
